# syntax=docker/dockerfile:1

FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

# Copy application source code into the image
COPY src ./src

EXPOSE 5000

CMD ["npm", "run", "dev"]